# Beepsky, Goonstation's replacement for a CI service like Travis, utilizing GitHub Actions
# Based on Turdis by Yogstation

name: Beepsky

on:
  pull_request:
    branches: master
  push:

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Cache SpacemanDMM
        uses: actions/cache@v1
        with:
          path: ~/SpacemanDMM
          key: ${{ runner.os }}-dreamchecker-${{ hashFiles('buildByond.conf')}}
          restore-keys: ${{ runner.os }}-dreamchecker

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1.3.3

      - name: Install Dependencies
        run: |
          tools/ci/install_build_tools.sh
          tools/ci/install_spaceman_dmm.sh dreamchecker
          touch +secret/__secret.dme

      - name: Misc Checks
        run: |
          tools/ci/check_filedirs.sh goonstation.dme
          tools/ci/build_tgui.sh
          tools/ci/check_grep.sh

      - name: Run Linter
        id: linter
        run: |
          ~/dreamchecker > ${GITHUB_WORKSPACE}/output-annotations.txt 2>&1

      - name: Annotate Linter
        uses: yogstation13/DreamAnnotate@9f2dbe51421affdecc6973c47d34b7f1009d77d3 # v1 - security concerns and all that shit
        if: always()
        with:
          outputFile: output-annotations.txt

  compile:
    name: Compile
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          curl https://raw.githubusercontent.com/goonstation/goonstation/master/tools/ci/sources.list | sudo tee /etc/apt/sources.list
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install libstdc++6:i386

      - name: Cache BYOND
        uses: actions/cache@v1
        with:
          path: ~/BYOND
          key: ${{ runner.os }}-byond-${{ hashFiles('buildByond.conf')}}
          restore-keys: ${{ runner.os }}-byond

      - name: Setup BYOND
        run: |
          tools/ci/install_byond.sh
          cd $GITHUB_WORKSPACE
          printenv
          echo "BYOND_SYSTEM=/home/runner/BYOND/byond" >> $GITHUB_ENV
          echo "/home/runner/BYOND/byond/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/home/runner/BYOND/byond/bin:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "MANPATH=/home/runner/BYOND/byond/man:$MANPATH" >> $GITHUB_ENV
          touch +secret/__secret.dme

      - name: Compile
        run: |
          tools/ci/dm.sh -DTRAVISBUILDING goonstation.dme

      - name: Prepare Artifacts
        run: |
          mkdir artifacts
          cp goonstation.dmb artifacts
          cp goonstation.rsc artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: DMB + RSC
          path: ${{github.workspace}}/artifacts


  compile_ass:
    name: "Compile for Ass Day"
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          curl https://raw.githubusercontent.com/goonstation/goonstation/master/tools/ci/sources.list | sudo tee /etc/apt/sources.list
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install libstdc++6:i386

      - name: Cache BYOND
        uses: actions/cache@v1
        with:
          path: ~/BYOND
          key: ${{ runner.os }}-byond-${{ hashFiles('buildByond.conf')}}
          restore-keys: ${{ runner.os }}-byond

      # Ass Jam occurs on the 13th of the month.
      - name: Setup BYOND
        run: |
          tools/ci/install_byond.sh
          cd $GITHUB_WORKSPACE
          printenv
          echo "BYOND_SYSTEM=/home/runner/BYOND/byond" >> $GITHUB_ENV
          echo "/home/runner/BYOND/byond/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/home/runner/BYOND/byond/bin:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "MANPATH=/home/runner/BYOND/byond/man:$MANPATH" >> $GITHUB_ENV
          touch +secret/__secret.dme
          sed -i 's/BUILD_TIME_DAY 01/BUILD_TIME_DAY 13/' _std/__build.dm


      - name: Compile
        run: |
          tools/ci/dm.sh -DTRAVISBUILDING -DTRAVIS_ASSJAM goonstation.dme

  compile_full:
    name: "Compile and Lint with Secret Submodule"
    runs-on: ubuntu-18.04
    if: |
      ((github.event_name == 'push' && github.repository == 'goonstation/goonstation') || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == 'goonstation/goonstation')) && !contains(github.event.head_commit.message, 'skip ci')
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: '${{ secrets.ROBUDDYBOT_PAT }}'

      - name: Install Dependencies
        run: |
          curl https://raw.githubusercontent.com/goonstation/goonstation/master/tools/ci/sources.list | sudo tee /etc/apt/sources.list
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install libstdc++6:i386

      - name: Cache BYOND
        uses: actions/cache@v1
        with:
          path: ~/BYOND
          key: ${{ runner.os }}-byond-${{ hashFiles('buildByond.conf')}}
          restore-keys: ${{ runner.os }}-byond

      - name: Setup BYOND
        run: |
          tools/ci/install_byond.sh
          cd $GITHUB_WORKSPACE
          printenv
          echo "BYOND_SYSTEM=/home/runner/BYOND/byond" >> $GITHUB_ENV
          echo "/home/runner/BYOND/byond/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/home/runner/BYOND/byond/bin:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "MANPATH=/home/runner/BYOND/byond/man:$MANPATH" >> $GITHUB_ENV

      - name: Cache SpacemanDMM
        uses: actions/cache@v1
        with:
          path: ~/SpacemanDMM
          key: ${{ runner.os }}-dreamchecker-${{ hashFiles('buildByond.conf')}}
          restore-keys: ${{ runner.os }}-dreamchecker

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1.3.3

      - name: Install Dependencies
        run: |
          tools/ci/install_spaceman_dmm.sh dreamchecker
          touch +secret/__secret.dme

      - name: Misc Checks
        run: |
          tools/ci/check_filedirs.sh goonstation.dme
          tools/ci/check_grep.sh

      - name: Run Linter
        id: linter
        run: |
          ~/dreamchecker > ${GITHUB_WORKSPACE}/output-annotations.txt 2>&1

      - name: Compile
        run: |
          tools/ci/dm.sh -DTRAVISBUILDING -DTRAVIS_SUB goonstation.dme

      - name: Annotate Linter
        uses: yogstation13/DreamAnnotate@9f2dbe51421affdecc6973c47d34b7f1009d77d3 # v1 - security concerns and all that shit
        if: always()
        with:
          outputFile: output-annotations.txt
