name: "Post Labeled PRs to the Forum"
on:
  pull_request_target:
    types: [labeled, closed, edited, reopened]

jobs:
  post-to-forums:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'goonstation/goonstation' && (github.event.action == 'labeled' && github.event.label.name == 'E-Input-Wanted' || github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'E-Input-Wanted')) }}
    steps:
    - name: Get The Script
      run: |
        wget "https://raw.githubusercontent.com/${{ github.repository }}/master/.github/post_to_forums.py"
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygithub requests
    - name: Post the thread
      run: |
        python post_to_forums.py
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        FORUM_URL: "https://forum.ss13.co"
        FORUM_PASSWORD: ${{ secrets.FORUM_PASSWORD }}
        FORUM_USERNAME: "github_bot"
        SUBFORUM_ID: 8 # Ideas & Suggestions
        POST_ICON: 11 # ‚Ñπ
        POST_ICON_CLOSED: 18 # üëé
        POST_ICON_MERGED: 19 # üëç
        SUBJECT_PREFIX: "[PR] "
        SUBJECT_PREFIX_CLOSED: "[CLOSED PR] "
        SUBJECT_PREFIX_MERGED: "[MERGED PR] "
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_BODY: ${{ github.event.pull_request.body }}
        PR_URL: ${{ github.event.pull_request.html_url }}
        PR_NUM: ${{ github.event.pull_request.number }}
        PR_STATE: ${{ github.event.pull_request.state }}
        PR_MERGED: ${{ github.event.pull_request.merged }}
