name: "Close stale PRs"
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          stale-pr-message: "This PR has been inactive for two weeks, and has been automatically marked as stale. This means it is at risk of being auto closed in another week. Please address any outstanding review items and ensure your PR is finished. If you are auto-staled anyway, ask developers if your PR will be merged. Once you have done any of the previous actions then you should request a developer remove the stale label on your PR, to reset the stale timer. If you feel no developer will respond in that time, you may wish to close this PR youself, while you seek developer comment, as you will then be able to reopen the PR yourself."
          days-before-pr-stale: 14
          days-before-pr-close: 7
          stale-pr-label: "S-Stale"
          exempt-pr-labels: "E-Certified-Organic,E-Contest,S-Testmerged"

          close-issue-message: "This issue has been marked as 'Needs Reproducing' for a month, and is being closed automatically. If you find a way to reproduce this bug, make another issue with more detailed reproduction steps."
          days-before-issue-stale: -1
          days-before-issue-close: 30
          only-issue-labels: "S-Needs-Reproducing"
          exempt-issue-labels: "E-Verified"
          ignore-issue-updates: true
          close-issue-reason: "not_planned"
